# Generated by Django 3.1.2 on 2021-09-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.IntegerField(default=150),
        ),
    ]
